[features]
seeds = false
skip-lint = false
[programs.localnet]
r15_shared_messageboard = "3Wbb4musZigEyTpbz287zufocXyi4ugjbGmp7Dr6khs9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./test-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
